spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/roomres}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:roomres}
    password: ${SPRING_DATASOURCE_PASSWORD:roomres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  sql:
    init:
      mode: never

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: warn
